/**
 * One-command demo setup: `npm run demo`
 *
 * Generates working credentials and seeds a shop that looks like a real
 * business, so the whole system can be shown without configuring anything.
 *
 * It relaxes exactly one guard: ADMIN_DEMO_MODE switches the admin sign-in off,
 * because a demo should not open with a password prompt. Everything else it
 * *configures* rather than bypasses — the affiliate portal and partner API
 * still fail closed when unconfigured. Everything it writes goes to .env.local,
 * which is gitignored, so no deployment inherits any of it. The credentials are
 * printed in the terminal, which is exactly why they must never be used
 * anywhere real.
 */

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_PATH = resolve(ROOT, ".env.local");
const DATA_DIR = resolve(ROOT, ".data");

const args = new Set(process.argv.slice(2));
const RESET = args.has("--reset");
const FORCE = args.has("--force");

const DEMO_ADMIN_PASSWORD = "demo-chef-ammar-2026";

function fail(message: string, hint?: string): never {
  console.error(`\n  ✗ ${message}`);
  if (hint) console.error(`    ${hint}`);
  console.error("");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Guards. Seeding invented orders into a real shop would be unrecoverable.
// ---------------------------------------------------------------------------

if (process.env.NODE_ENV === "production") {
  fail("Refusing to run with NODE_ENV=production.", "This seeds fake orders and writes demo credentials.");
}

const existingEnv = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "";
const configuredDbUrl =
  process.env.DATABASE_URL ?? /^DATABASE_URL=(.+)$/m.exec(existingEnv)?.[1]?.trim();

if (configuredDbUrl && !FORCE) {
  const isLocal = /@(localhost|127\.0\.0\.1|\[::1\])[:/]/.test(configuredDbUrl);
  if (!isLocal) {
    fail(
      "DATABASE_URL points at a remote database.",
      "Seeding demo orders there would mix invented data into a real shop.\n" +
        "    Unset DATABASE_URL to use the local demo database, or pass --force if you\n" +
        "    genuinely mean to seed the remote one.",
    );
  }
}

// ---------------------------------------------------------------------------
// Credentials. Existing values are kept; only missing keys are added, so a
// re-run never silently changes a password someone is already using.
// ---------------------------------------------------------------------------

const secret = () => randomBytes(32).toString("base64url");

const wanted: Record<string, string> = {
  // Opens the admin area without a sign-in, so the demo is one command and no
  // password. Only ever written here, into a gitignored file — a deployment
  // has to opt in through its own environment.
  ADMIN_DEMO_MODE: "1",
  // Still configured, so turning the demo flag off leaves a working sign-in
  // rather than a disabled admin area.
  ADMIN_PASSWORD: DEMO_ADMIN_PASSWORD,
  ADMIN_SESSION_SECRET: secret(),
  AFFILIATE_SESSION_SECRET: secret(),
  ORDER_ACCESS_SECRET: secret(),
  PARTNER_API_KEY: secret(),
  AGENT_NAME: "KretivWork",
  AGENT_FEE_PER_SALE: "2",
  AGENT_FEE_BASIS: "order",
};

const lines = existingEnv ? existingEnv.split("\n") : [];
const present = new Set(
  lines.map((l) => /^([A-Z_]+)=/.exec(l.trim())?.[1]).filter(Boolean) as string[],
);

const added: string[] = [];
for (const [key, value] of Object.entries(wanted)) {
  if (!present.has(key)) {
    lines.push(`${key}=${value}`);
    added.push(key);
  }
}

if (added.length > 0) {
  const header = existingEnv ? "" : "# Generated by `npm run demo` — local demo only, never deploy these.\n";
  writeFileSync(ENV_PATH, header + lines.filter(Boolean).join("\n") + "\n");
}

// Make the values available to the seeding below in this same process.
for (const line of readFileSync(ENV_PATH, "utf8").split("\n")) {
  const match = /^([A-Z_]+)=(.*)$/.exec(line.trim());
  if (match && !process.env[match[1]]) process.env[match[1]] = match[2];
}

if (RESET && existsSync(DATA_DIR)) {
  rmSync(DATA_DIR, { recursive: true, force: true });
  console.log("  · cleared the local demo database");
}

// Imported after the environment is in place, so the store reads the right config.
const { DEMO_AFFILIATE_PASSWORD, seedDemoData } = await import("./seed-demo.mts");
const result = await seedDemoData();

const envValue = (key: string) =>
  /^([A-Z_]+)=(.*)$/m.exec(readFileSync(ENV_PATH, "utf8").split("\n").find((l) => l.startsWith(`${key}=`)) ?? "")?.[2] ??
  "(not set)";

console.log(`
  Chef Ammar demo is ready.

  Seeded
    ${result.affiliates} affiliates · ${result.orders} orders · ${result.paid} paid
    ${result.referred} of them through a referral link

  Start it
    npm run dev            then open http://localhost:3000

  Admin — open http://localhost:3000/admin
    No sign-in: ADMIN_DEMO_MODE=1 is set in .env.local, so the login is off
    and every admin page shows a red banner saying so.
    Orders      /admin/orders
    Affiliates  /admin/affiliates

  To put the sign-in back
    Remove ADMIN_DEMO_MODE from .env.local, then the password is
      ${DEMO_ADMIN_PASSWORD}

  Affiliate portal — open http://localhost:3000/affiliate
    Standalone: affiliates sign in themselves and see only their own orders.
    In demo mode the sign-in page lists the seeded affiliates as one-click
    buttons. Their passwords are set too, if you want to try the real form:
      CHEFCLUB / DAPURKITA / AMINA10   password  ${DEMO_AFFILIATE_PASSWORD}

  Partner API (the central dashboard's feed)
    curl -H "Authorization: Bearer ${envValue("PARTNER_API_KEY")}" \\
      http://localhost:3000/api/partner/summary

  Notes
    · Payments are simulated — no CHIP credentials, so no money moves.
    · Orders live in a local database under .data/, not Postgres.
    · These credentials are printed in a terminal. Local demo only.

  Re-run with --reset to wipe the data and start again.
`);
